# Deliberately excluded:
# "בר", "פז", "מגה" — 2-3 chars, substring-match inside unrelated words.
# "מקס" alone — collides with CREDIT_CARD_COMPANY_NAME_FRAGMENTS in bank/classify.py and
#   would file the Max card's lump-sum payment as Shopping. Use "מקס סטוק" for the store.
# "העברה בBIT" — a Bit peer transfer's purpose is unknowable; leave it Uncategorized so
#   the user categorizes per-instance.

SEED_KEYWORDS: list[tuple[str, str]] = [
    ("שופרסל", "food"),
    ("רמי לוי", "food"),
    ("יוחננוף", "food"),
    ("ויקטורי", "food"),
    ("אושר עד", "food"),
    ("טיב טעם", "food"),
    ("יינות ביתן", "food"),
    ("סופר אל הים", "food"),
    ("בקס מרקט", "food"),
    ("אמ.פי.אם", "food"),
    ("am:pm", "food"),
    ("מיני מרקט", "food"),
    ("זול ובגדול", "food"),
    ("יאנגו דלי", "food"),
    ("קרפור", "food"),
    ("מחסני השוק", "food"),
    ("פרש מרקט", "food"),
    ("חצי חינם", "food"),

    ("wolt", "Going Out"),
    ("וולט", "Going Out"),
    ("10bis", "Going Out"),
    ("תן ביס", "Going Out"),
    ("מסעדת", "Going Out"),
    ("מסעדה", "Going Out"),
    ("קפה", "Going Out"),
    ("cafe", "Going Out"),
    ("coffee", "Going Out"),
    ("ארומה", "Going Out"),
    ("לנדוור", "Going Out"),
    ("סודסקו", "Going Out"),
    ("קופיקס", "Going Out"),
    ("cofix", "Going Out"),
    ("רולדין", "Going Out"),
    ("פיצה", "Going Out"),
    ("pizza", "Going Out"),
    ("דומינוס", "Going Out"),
    ("בורגר", "Going Out"),
    ("burger", "Going Out"),
    ("mcdonald", "Going Out"),
    ("מקדונלדס", "Going Out"),
    ("kfc", "Going Out"),
    ("מזנוני", "Going Out"),
    ("מזנון", "Going Out"),
    ("קיוסק", "Going Out"),
    ("צאקולי", "Going Out"),
    ("נאייקס", "Going Out"),
    ("hataco", "Going Out"),
    ("ביסטרו", "Going Out"),
    ("שווארמה", "Going Out"),
    ("פלאפל", "Going Out"),
    ("חומוס", "Going Out"),
    ("סושי", "Going Out"),

    ("הוראת-קבע", "Bills"),
    ("חברת החשמל", "Bills"),
    ("מקורות", "Bills"),
    ("מי אביבים", "Bills"),
    ("בזק", "Bills"),
    ("hot", "Bills"),
    ("פרטנר", "Bills"),
    ("partner", "Bills"),
    ("סלקום", "Bills"),
    ("cellcom", "Bills"),
    ("פלאפון", "Bills"),
    ("גולן טלקום", "Bills"),
    ("עיריית", "Bills"),
    ("עירית", "Bills"),
    ("ארנונה", "Bills"),
    ("ביטוח", "Bills"),
    ("הראל", "Bills"),
    ("מגדל", "Bills"),
    ("הפניקס", "Bills"),
    ("מנורה מבטחים", "Bills"),
    ("דמי כרטיס", "Bills"),
    ("עמלת", "Bills"),
    ("מפעולות", "Bills"),
    ("מאוחדת", "Bills"),
    ("כללית", "Bills"),
    ("מכבי", "Bills"),

    ("פז אפליק", "Car"),
    ("yellow", "Car"),
    ("דלק", "Car"),
    ("delek", "Car"),
    ("סונול", "Car"),
    ("sonol", "Car"),
    ("דור אלון", "Car"),
    ("פנגו", "Car"),
    ("pango", "Car"),
    ("cellopark", "Car"),
    ("סלופארק", "Car"),
    ("אחוזות החוף", "Car"),
    ("חניון", "Car"),
    ("חניה", "Car"),
    ("כביש 6", "Car"),
    ("מוסך", "Car"),
    ("צמיג", "Car"),
    ("שטיפת", "Car"),
    ("רישוי", "Car"),
    ("שלמה סיקסט", "Car"),
    ("שלמה פסגה", "Car"),
    ("אלדן", "Car"),
    ("hertz", "Car"),
    ("avis", "Car"),

    ("netflix", "Entertainment"),
    ("נטפליקס", "Entertainment"),
    ("spotify", "Entertainment"),
    ("youtube", "Entertainment"),
    ("disney", "Entertainment"),
    ("hbo", "Entertainment"),
    ("apple.com/bill", "Entertainment"),
    ("itunes", "Entertainment"),
    ("google play", "Entertainment"),
    ("anthropic", "Entertainment"),
    ("openai", "Entertainment"),
    ("chatgpt", "Entertainment"),
    ("amazon prime", "Entertainment"),
    ("steam", "Entertainment"),
    ("playstation", "Entertainment"),
    ("nintendo", "Entertainment"),
    ("xbox", "Entertainment"),
    ("patreon", "Entertainment"),
    ("audible", "Entertainment"),
    ("סינמה", "Entertainment"),
    ("cinema", "Entertainment"),
    ("יס פלאנט", "Entertainment"),
    ("yes planet", "Entertainment"),
    ("סטימצקי", "Entertainment"),
    ("צומת ספרים", "Entertainment"),

    ("amazon", "Shopping"),
    ("אמזון", "Shopping"),
    ("aliexpress", "Shopping"),
    ("temu", "Shopping"),
    ("ebay", "Shopping"),
    ("shein", "Shopping"),
    ("terminal x", "Shopping"),
    ("castro", "Shopping"),
    ("קסטרו", "Shopping"),
    ("fox", "Shopping"),
    ("פוקס", "Shopping"),
    ("zara", "Shopping"),
    ("h&m", "Shopping"),
    ("ksp", "Shopping"),
    ("ivory", "Shopping"),
    ("מחסני חשמל", "Shopping"),
    ("הום סנטר", "Shopping"),
    ("ikea", "Shopping"),
    ("איקאה", "Shopping"),
    ("מקס סטוק", "Shopping"),
    ("max stock", "Shopping"),
    ("גולף", "Shopping"),
    ("אורבניקה", "Shopping"),
    ("רנואר", "Shopping"),
    ("המשביר", "Shopping"),
    ("סופר פארם", "Shopping"),
    ("super-pharm", "Shopping"),
    ("ניו פארם", "Shopping"),

    ("פט בסט", "pet"),
    ("animal", "pet"),
    ("וטרינר", "pet"),
    ("כלבו", "pet"),
]
